[package]
name = "wal-cli"
description = "cli to control pywal"
readme = "README.md"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Kian Shepherd <Kianshepherd73@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
ron = "*"
serde = "*"
regex = "*"
